'use strict';
(function () {
  var USERS_QUANTITY = 25;
  var LIKES_MAX = 200;
  var LIKES_MIN = 15;
  var COMMENTS_MAX = 5;
  var AVATAR_MAX = 6;

  var MAX_COMMENT_LENGTH = 140;

  var PICTURE_SIZE = 100;
  var PICTURE_EFFECT = 100;

  window.Parameters = {
    USERS_QUANTITY: USERS_QUANTITY,
    LIKES_MAX: LIKES_MAX,
    LIKES_MIN: LIKES_MIN,
    COMMENTS_MAX: COMMENTS_MAX,
    AVATAR_MAX: AVATAR_MAX,
    MAX_COMMENT_LENGTH: MAX_COMMENT_LENGTH,
    PICTURE_SIZE: PICTURE_SIZE,
    PICTURE_EFFECT: PICTURE_EFFECT
  };
})();
